[package]
name = "pack"
version = "0.2.14"
authors = ["maralla <maralla.ai@gmail.com>"]
edition = "2018"

[dependencies]
yaml-rust2 = "0.10"
walkdir = "2"
termion = "1.0"
num_cpus = "1.0"
dirs = "5"
signal-hook = "0.3"
libc = "0.2.66"
crossbeam-channel = "0.5"
log = { version = "0.4", features = ["std"] }

[dependencies.clap]
version = "4"
features = ["string"]

[dependencies.clap_complete]
version = "4"

[dependencies.git2]
version = "0.20"
default-features = false
features = ["ssh", "https"]

[features]
default = ["vendored-openssl"]
vendored-openssl = ["git2/vendored-openssl"]
