use std::fs::{self, File};
use std::io::{Read, Write};
use std::env;
use std::path::{Path, PathBuf};
use std::fmt;
use std::process;

use {Result, Error};

use yaml_rust::{Yaml, YamlLoader, YamlEmitter};
use yaml_rust::yaml::Hash;

const PACK_PLUGIN_FILE: &'static str = "_pack.vim";
const PLUGIN_HEADER: &'static str = "\" Generated by pack. DO NOT EDIT!

scriptencoding utf-8

function! s:do_cmd(cmd, bang, start, end, args)
    exec printf('%s%s%s %s', (a:start == a:end ? '' : (a:start.','.a:end)), a:cmd, a:bang, a:args)
endfunction
";

const PACKFILE_HEADER: &'static [u8] = b"# vim: ft=yaml
#
# Generated by pack.

";

lazy_static! {
    static ref BASE_DIR: PathBuf =
        env::var("VIM_CONFIG_PATH").map(|p| PathBuf::from(p)).unwrap_or_else(|_| {
            let home = env::home_dir().expect("No home directory found");
            home.join(".vim")
        });
    static ref PACK_DIR: PathBuf = (*BASE_DIR).join("pack");
    static ref PACK_CONFIG_DIR: PathBuf = (*BASE_DIR).join(".pack");
    static ref PACK_FILE: PathBuf = (*PACK_CONFIG_DIR).join("packfile");
    static ref PACK_PLUGIN_DIR: PathBuf = (*BASE_DIR).join("plugin");
}

#[derive(Debug, Clone)]
pub struct Package {
    pub name: String,
    pub category: String,
    pub opt: bool,
    /// Load this package on this command
    pub load_command: Option<String>,
    /// Load this package for these types
    pub for_types: Vec<String>,
    /// Build command for this package
    pub build_command: Option<String>,
    /// Local plugin
    pub local: bool,
}

impl Package {
    pub fn new(name: &str, category: &str, opt: bool) -> Package {
        Package {
            name: name.to_string(),
            category: category.to_string(),
            opt: opt,
            load_command: None,
            for_types: Vec::new(),
            build_command: None,
            local: false,
        }
    }

    pub fn is_installed(&self) -> bool {
        self.path().is_dir()
    }

    pub fn set_category<T: Into<String>>(&mut self, cat: T) {
        self.category = cat.into();
    }

    pub fn set_opt(&mut self, opt: bool) {
        self.opt = opt;
    }

    pub fn set_load_command(&mut self, cmd: &str) {
        self.load_command = Some(cmd.to_string())
    }

    pub fn set_types(&mut self, types: Vec<String>) {
        self.for_types = types
    }

    pub fn set_build_command(&mut self, cmd: &str) {
        self.build_command = Some(cmd.to_string())
    }

    pub fn from_yaml(doc: &Yaml) -> Result<Package> {
        let name = doc["name"].as_str().map(|s| s.to_string()).ok_or(Error::Format)?;
        let opt = doc["opt"].as_bool().ok_or(Error::Format)?;
        let category = doc["category"].as_str().map(|s| s.to_string()).ok_or(Error::Format)?;
        let cmd = doc["on"].as_str().map(|s| s.to_string());
        let build = doc["build"].as_str().map(|s| s.to_string());
        let is_local = doc["local"].as_bool().unwrap_or(false);

        let types = match doc["for"].as_vec() {
            Some(f) => {
                let mut types = Vec::with_capacity(f.len());
                for e in f {
                    types.push(e.as_str().map(|s| s.to_string()).ok_or(Error::Format)?);
                }
                types
            }
            None => vec![],
        };

        Ok(Package {
            name: name,
            category: category,
            opt: opt,
            load_command: cmd,
            for_types: types,
            build_command: build,
            local: is_local,
        })
    }

    pub fn into_yaml(self) -> Yaml {
        let mut doc = Hash::new();
        doc.insert(Yaml::from_str("name"), Yaml::from_str(&self.name));
        doc.insert(Yaml::from_str("category"), Yaml::from_str(&self.category));
        doc.insert(Yaml::from_str("opt"), Yaml::Boolean(self.opt));
        doc.insert(Yaml::from_str("local"), Yaml::Boolean(self.local));
        if let Some(ref c) = self.load_command {
            doc.insert(Yaml::from_str("on"), Yaml::from_str(c));
        }
        if let Some(ref c) = self.build_command {
            doc.insert(Yaml::from_str("build"), Yaml::from_str(c));
        }
        if !self.for_types.is_empty() {
            let types = self.for_types.iter().map(|e| Yaml::from_str(e)).collect::<Vec<Yaml>>();
            doc.insert(Yaml::from_str("for"), Yaml::Array(types));
        }
        Yaml::Hash(doc)
    }

    #[inline]
    fn basename(&self) -> &str {
        Path::new(&self.name).file_name().iter().filter_map(|e| e.to_str()).next().unwrap_or("")
    }

    pub fn path(&self) -> PathBuf {
        let repo = if self.local {
            self.basename()
        } else {
            let (_, repo) = self.repo();
            repo
        };
        if self.opt {
            PACK_DIR.join(&self.category).join("opt").join(repo)
        } else {
            PACK_DIR.join(&self.category).join("start").join(repo)
        }
    }

    pub fn config_path(&self) -> PathBuf {
        let name = if self.local {
            self.basename().to_string()
        } else {
            self.name.replace("/", "-")
        };
        let fname = if name.ends_with(".vim") {
            name
        } else {
            format!("{}.vim", &name)
        };
        PACK_CONFIG_DIR.join(fname)
    }

    pub fn repo(&self) -> (&str, &str) {
        let mut info = self.name.splitn(2, "/");
        let user = info.next().unwrap_or("");
        let repo = info.next().unwrap_or("");
        (user, repo)
    }

    pub fn try_build(&self) -> Result<()> {
        if let Some(ref c) = self.build_command {
            let path = self.path();
            let p = process::Command::new("sh").arg("-c")
                .arg(c)
                .stdout(process::Stdio::piped())
                .stderr(process::Stdio::piped())
                .current_dir(&path)
                .spawn()?;
            let output = p.wait_with_output()?;
            if !output.status.success() {
                let err = String::from_utf8(output.stderr)
                    .unwrap_or(String::from("No error output!"));
                return Err(Error::Build(err));
            }
        }
        Ok(())
    }
}

impl fmt::Display for Package {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let name = if self.opt { "opt" } else { "start" };
        let on = match self.load_command {
            Some(ref c) => format!(" [Load on `{}`]", c),
            None => "".to_string(),
        };

        let types = if !self.for_types.is_empty() {
            let types = self.for_types.join(",");
            format!(" [For {}]", types)
        } else {
            "".to_string()
        };
        write!(f,
               "{} => pack/{}/{}{}{}",
               &self.name,
               &self.category,
               name,
               on,
               types)
    }
}

pub fn fetch() -> Result<Vec<Package>> {
    if PACK_FILE.is_file() {
        fetch_from_packfile(&*PACK_FILE)
            .map_err(|e| Error::PackFile(format!("Fail to parse packfile: {}", e)))
    } else {
        Ok(vec![])
    }
}

fn fetch_from_packfile<P: AsRef<Path>>(packfile: P) -> Result<Vec<Package>> {
    let mut data = String::new();
    File::open(packfile.as_ref())?.read_to_string(&mut data)?;
    let docs = YamlLoader::load_from_str(&data)?;

    let mut ret = Vec::new();
    if !docs.is_empty() {
        if let Some(doc) = docs[0].as_vec() {
            for d in doc {
                ret.push(Package::from_yaml(d)?);
            }
        }
    }
    Ok(ret)
}

pub fn save(packs: Vec<Package>) -> Result<()> {
    let packs = packs.into_iter().map(|e| e.into_yaml()).collect::<Vec<Yaml>>();
    let doc = Yaml::Array(packs);
    let mut out = String::new();
    {
        let mut emitter = YamlEmitter::new(&mut out);
        emitter.dump(&doc)?;
    }
    if !PACK_CONFIG_DIR.is_dir() {
        fs::create_dir_all(&*PACK_CONFIG_DIR)?;
    }
    let mut f = File::create(&*PACK_FILE)?;
    f.write(PACKFILE_HEADER)?;
    f.write(out.as_bytes())?;
    Ok(())
}

pub fn update_pack_plugin(packs: &[Package]) -> Result<()> {
    if !PACK_PLUGIN_DIR.is_dir() {
        fs::create_dir_all(&*PACK_PLUGIN_DIR)?;
    }

    let mut f = File::create(PACK_PLUGIN_DIR.join(PACK_PLUGIN_FILE))?;
    f.write_all(format!("{}\n\n", PLUGIN_HEADER).as_bytes())?;

    let mut buf = String::new();
    for (p, path) in packs.iter().map(|x| (x, x.config_path())) {
        buf.clear();
        let mut written = false;

        if let Some(ref c) = p.load_command {
            f.write_all(format!("\" {}\n", &p.name).as_bytes())?;
            written = true;
            let (_, repo) = p.repo();
            let msg = format!("command! -nargs=* -range -bang {cmd} packadd {repo} | \
                               call s:do_cmd('{cmd}', \"<bang>\", <line1>, <line2>, <q-args>)\n\n",
                              cmd = c,
                              repo = repo);
            f.write_all(msg.as_bytes())?;
        }

        if !p.for_types.is_empty() {
            if !written {
                f.write_all(format!("\" {}\n", &p.name).as_bytes())?;
                written = true;
            }
            let (_, repo) = p.repo();
            let msg = format!("autocmd FileType {} packadd {}\n\n",
                              p.for_types.join(","),
                              repo);
            f.write_all(msg.as_bytes())?;
        }

        if path.is_file() {
            File::open(&path)?.read_to_string(&mut buf)?;
            if !written {
                f.write_all(format!("\" {}\n", &p.name).as_bytes())?;
            }
            f.write_all(format!("{}\n", &buf).as_bytes())?;
        }
    }
    Ok(())
}
