on:
  pull_request:
    types: [synchronize, closed]

name: debug

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo name=${{ github.event_name }} action=${{ github.event.action }} state=${{ github.event.pull_request.state }} title=${{ github.event.pull_request.title }} base_branch=${{ github.event.pull_request.base.ref }}
