on: [pull_request]

name: debug

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: echo state=${{ github.event.state }} title=${{ github.event.title }} base_branch=${{ github.event.base.ref }}
